language: scala

scala:
  - 2.13.1

services: docker

jdk:
  - openjdk8
  - openjdk11

sbt_args: --color=always

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

before_script:
  # https://hub.docker.com/r/openio/openstack-keystone
  # https://github.com/open-io/dockerfiles/blob/master/openstack-keystone/queens/keystone-v3.sh
  - |
    docker run -d -e IPADDR=0.0.0.0 -p 5000:5000 -p 35357:35357 --name=dev-keystone openio/openstack-keystone:queens

script:
  - sbt compile
  - sbt coverage test

#after_success:
#  - sbt coverageReport codacyCoverage
#  - bash <(curl -s https://codecov.io/bash)